// demo/counter-vue/js/Master.vue
<template>
  <div>
    <errors-display :data="errors"></errors-display>
    <qrcode-display
      width="160"
      height="160"
      :data="makeRemotePeerUrl(peerId)"
      v-if="peerId"
    ></qrcode-display>
    <OpenRemote :peerId="peerId" />
    <p>
      Global counter:
      <counter-display
        class="global-counter"
        :data="globalCount(remotesList)"
      />
    </p>
    <remotes-list :data="remotesList"></remotes-list>
    <console-display :data="reversedLogs" />
  </div>
</template>

<script>
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { usePeer } from "@webrtc-remote-control/vue";

import "../../shared/js/components/errors-display";
import "../../shared/js/components/qrcode-display";
import "../../shared/js/components/counter-display";
import "../../shared/js/components/remotes-list";
import "../../shared/js/components/console-display";

import OpenRemote from "./OpenRemote.vue";

import {
  persistCountersToStorage,
  getCountersFromStorage,
} from "../../shared/js/counter.master.persistance";
import {
  counterReducer,
  globalCount,
} from "../../shared/js/counter.master.logic";
import { useLogger } from "./common";

function makeRemotePeerUrl(peerId) {
  return `${
    window.location.origin +
    window.location.pathname
      .replace(/\/$/, "")
      .split("/")
      .slice(0, -1)
      .join("/")
  }/index.html#${peerId}`;
}

export default {
  components: { OpenRemote },
  setup() {
    const { logs, logger } = useLogger([]);
    const peerId = ref(null);
    const remotesList = ref([]);
    const errors = ref(null);
    const reversedLogs = computed(() => [...logs.value].reverse());

    const { ready, api, peer, peerReady, humanizeError } = usePeer();

    const onRemoteConnect = ({ id }) => {
      const countersFromStorage = getCountersFromStorage();
      logger.log({ event: "remote.connect", payload: { id } });
      remotesList.value = [
        ...remotesList.value,
        {
          counter: countersFromStorage?.[id] ?? 0,
          peerId: id,
        },
      ];
    };
    const onRemoteDisconnect = ({ id }) => {
      logger.log({ event: "remote.disconnect", payload: { id } });
      remotesList.value = remotesList.value.filter(
        ({ peerId }) => peerId !== id
      );
    };
    const onData = ({ id }, data) => {
      logger.log({ event: "data", data, id });
      const newRemotesListValue = counterReducer(remotesList.value, {
        data,
        id,
      });
      persistCountersToStorage(newRemotesListValue);
      remotesList.value = newRemotesListValue;
    };
    const onPeerError = (error) => {
      peerId.value = null;
      logger.error({ event: "error", error });
      errors.value = [humanizeError.value(error)];
    };

    watch([peerReady], (_, __, onCleanup) => {
      if (peer) {
        peer.value.on("error", onPeerError);
      }
      onCleanup(() => {
        if (peer) {
          peer.value.off("error", onPeerError);
        }
      });
    });

    watch([ready], ([currentReady], [prevReady], onCleanup) => {
      console.log(
        "Master.watchEffect",
        { currentReady, prevReady },
        ready.value,
        api.value.on
      );
      if (ready.value) {
        peerId.value = peer.value.id;
        logger.log({
          event: "open",
          comment: "Master connected",
          payload: { id: peer.value.id },
        });
        api.value.on("remote.connect", onRemoteConnect);
        api.value.on("remote.disconnect", onRemoteDisconnect);
        api.value.on("data", onData);
      }
      onCleanup(() => {
        console.log("Master.vue.cleanup");
        if (ready.value) {
          api.value.off("remote.connect", onRemoteConnect);
          api.value.off("remote.disconnect", onRemoteDisconnect);
          api.value.off("data", onData);
        }
      });
    });

    // manage `ping` / `ping all` buttons

    const onPingAll = () => {
      if (ready.value) {
        api.value.sendAll({
          type: "PING",
          date: new Date(),
        });
      }
    };
    const onPing = ({ detail: { id } }) => {
      if (ready.value) {
        api.value.sendTo(id, {
          type: "PING",
          date: new Date(),
        });
      }
    };

    onMounted(() => {
      document
        .querySelector("remotes-list")
        .addEventListener("pingAll", onPingAll);
      document.querySelector("remotes-list").addEventListener("ping", onPing);
    });

    // cleanup
    onUnmounted(() => {
      document
        .querySelector("remotes-list")
        .removeEventListener("pingAll", onPingAll);
      document
        .querySelector("remotes-list")
        .removeEventListener("ping", onPing);
    });

    return {
      peerId,
      remotesList,
      errors,
      makeRemotePeerUrl,
      logs,
      reversedLogs,
      globalCount,
    };
  },
};
</script>

// demo/counter-react/js/Master.jsx
import React, { useEffect, useState } from "react";
import { usePeer } from "@webrtc-remote-control/react";

import ErrorsDisplay from "../../shared/js/components/ErrorsDisplay";
import QrcodeDisplay from "../../shared/js/components/QrcodeDisplay";
import OpenRemote from "./OpenRemote";
import CounterDisplay from "../../shared/js/components/CounterDisplay";
import RemotesList from "./RemotesList";
import ConsoleDisplay from "../../shared/js/components/ConsoleDisplay";
import DirectLinkToSourceCode from "./DirectLinkToSource";

import {
  persistCountersToStorage,
  getCountersFromStorage,
} from "../../shared/js/counter.master.persistance";
import {
  counterReducer,
  globalCount,
} from "../../shared/js/counter.master.logic";
import { useLogger } from "../../shared/js/react-common";

function makeRemotePeerUrl(peerId) {
  return `${
    window.location.origin +
    window.location.pathname
      .replace(/\/$/, "")
      .split("/")
      .slice(0, -1)
      .join("/")
  }/index.html#${peerId}`;
}

export default function Master() {
  const { logs, logger } = useLogger([]);
  const [peerId, setPeerId] = useState(null);
  const [remotesList, setRemotesList] = useState([]);
  const [errors, setErrors] = useState(null);

  const { ready, api, peer, humanizeError } = usePeer();

  const onRemoteConnect = ({ id }) => {
    const countersFromStorage = getCountersFromStorage();
    logger.log({ event: "remote.connect", payload: { id } });
    setRemotesList((counters) => [
      ...counters,
      { counter: countersFromStorage?.[id] ?? 0, peerId: id },
    ]);
  };
  const onRemoteDisconnect = ({ id }) => {
    logger.log({ event: "remote.disconnect", payload: { id } });
    setRemotesList((counters) =>
      // eslint-disable-next-line no-shadow
      counters.filter(({ peerId }) => peerId !== id),
    );
  };
  const onData = ({ id }, data) => {
    logger.log({ event: "data", data, id });
    setRemotesList((counters) => {
      const state = counterReducer(counters, { data, id });
      persistCountersToStorage(state);
      return state;
    });
  };
  const onPeerError = (error) => {
    setPeerId(null);
    logger.error({ event: "error", error });
    setErrors([humanizeError(error)]);
  };

  useEffect(() => {
    if (peer) {
      peer.on("error", onPeerError);
    }
    return () => {
      if (peer) {
        peer.off("error", onPeerError);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [peer]);

  useEffect(() => {
    if (ready) {
      setPeerId(peer.id);
      logger.log({
        event: "open",
        comment: "Master connected",
        payload: { id: peer.id },
      });
      api.on("remote.connect", onRemoteConnect);
      api.on("remote.disconnect", onRemoteDisconnect);
      api.on("data", onData);
    }
    return () => {
      console.log("Master.jsx.cleanup");
      if (ready) {
        api.off("remote.connect", onRemoteConnect);
        api.off("remote.disconnect", onRemoteDisconnect);
        api.off("data", onData);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ready]);
  return (
    <>
      <ErrorsDisplay data={errors} />
      {peerId ? <QrcodeDisplay data={makeRemotePeerUrl(peerId)} /> : null}
      <OpenRemote peerId={peerId} />
      <p>
        Global counter: <CounterDisplay count={globalCount(remotesList)} />
      </p>
      <RemotesList
        data={remotesList}
        onPingAll={() => {
          if (ready) {
            api.sendAll({
              type: "PING",
              date: new Date(),
            });
          }
        }}
        onPing={(id) => {
          if (ready) {
            api.sendTo(id, {
              type: "PING",
              date: new Date(),
            });
          }
        }}
      />
      <ConsoleDisplay data={[...logs].reverse()} />
      <DirectLinkToSourceCode mode="master" />
    </>
  );
}
