// demo/accelerometer-graph/js/App.jsx
/* eslint-disable no-nested-ternary */
import React, { useState, useEffect } from "react";

import { WebRTCRemoteControlProvider } from "@webrtc-remote-control/react";

import { getPeerjsConfig } from "../../shared/js/common-peerjs";

import Master from "./Master";
import Remote from "./Remote";
import FooterDisplay from "../../shared/js/components/Footer";

export default function App() {
  console.log("App render");
  const [mode, setMode] = useState(null);
  useEffect(() => {
    setMode(window.location.hash ? "remote" : "master");
  }, []);
  return (
    <>
      {mode ? (
        <WebRTCRemoteControlProvider
          mode={mode}
          init={({ getPeerId }) =>
            new Peer(
              getPeerId(),
              // line bellow is optional - you can rely on the signaling server exposed by peerjs
              getPeerjsConfig()
            )
          }
          masterPeerId={
            (window.location.hash && window.location.hash.replace("#", "")) ||
            null
          }
          sessionStorageKey="webrtc-remote-control-peer-id-accelerometer-graph"
        >
          {mode === "remote" ? <Remote /> : <Master />}
        </WebRTCRemoteControlProvider>
      ) : (
        "Loading ..."
      )}
      <FooterDisplay from="2022" to={new Date().getFullYear()} />
    </>
  );
}

// demo/counter-vue/js/App.vue
<template>
  <div>
    <Master v-if="mode === 'master'" key="master" />
    <Remote v-if="mode === 'remote'" key="remote" />
    <footer-display from="2022" :to="new Date().getFullYear()" />
  </div>
</template>

<script>
import { onBeforeMount, ref } from "vue";

import { provideWebTCRemoteControl } from "@webrtc-remote-control/vue";

import { getPeerjsConfig } from "../../shared/js/common-peerjs";

import "../../shared/js/components/footer-display";

import Master from "./Master.vue";
import Remote from "./Remote.vue";

export default {
  components: { Master, Remote },
  setup() {
    const mode = ref(null);
    onBeforeMount(() => {
      mode.value = window.location.hash ? "remote" : "master";
      provideWebTCRemoteControl(
        ({ getPeerId }) =>
          new Peer(
            getPeerId(),
            // line bellow is optional - you can rely on the signaling server exposed by peerjs
            getPeerjsConfig(),
          ),
        mode.value,
        {
          masterPeerId:
            (window.location.hash && window.location.hash.replace("#", "")) ||
            null,
          sessionStorageKey: "webrtc-remote-control-peer-id-vue",
        },
      );
    });
    return {
      mode,
    };
  },
};
</script>
