// demo/counter-react/js/RemoteNameControl.jsx
import React from "react";
import PropTypes from "prop-types";

export default function RemoteNameControl({
  onChangeName,
  onConfirmName,
  name,
  disabled,
}) {
  return (
    <form
      className="form-set-name"
      action="."
      onSubmit={(e) => {
        e.preventDefault();
        onConfirmName(e.target.name.value);
      }}
      disabled={disabled}
    >
      <label>
        <input
          type="text"
          placeholder="Enter name"
          onChange={(e) => onChangeName(e.target.value)}
          value={name}
          disabled={disabled}
        />
        <button type="submit" disabled={disabled}>
          OK
        </button>
      </label>
    </form>
  );
}

RemoteNameControl.propTypes = {
  onChangeName: PropTypes.func,
  onConfirmName: PropTypes.func,
  name: PropTypes.string,
  disabled: PropTypes.bool,
};

// demo/counter-vue/js/RemoteNameControl.vue
<template>
  <form
    class="form-set-name"
    action="."
    @submit="
      (e) => {
        e.preventDefault();
        onConfirmName?.();
      }
    "
    :disabled="disabled"
  >
    <label>
      <input
        type="text"
        placeholder="Enter name"
        @change="(e) => onChangeName?.((e.target as HTMLInputElement).value)"
        :value="name"
        :disabled="disabled"
      />
      <button type="submit" :disabled="disabled">OK</button>
    </label>
  </form>
</template>

<script setup lang="ts">
defineProps<{
  onChangeName?: (value: string) => void;
  onConfirmName?: () => void;
  name?: string;
  disabled?: boolean;
}>();
</script>
